version: "3"
services:
  sqlite3:
    image: nouchka/sqlite3:latest
    container_name: sqlite3
    stdin_open: true
    tty: true
    ports:
      - 27017:27017
    volumes:
      - ./db/:/root/db/

  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unsplsh_thumbnails
    ports:
      - 8000:80
    volumes:
      - ./thumb_app/:/code/app
      - ./db/:/root/db/
